sonar.organization=robertobado
sonar.projectKey=robertobado_netsk8-navigator

sonar.sources=backend,frontend/src
sonar.exclusions=frontend/src/assets/**,**/dist/**,**/node_modules/**,**/coverage/**

sonar.go.coverage.reportPaths=backend/coverage.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
