#!/bin/bash
# Assembles "Netsk8 Navigator.app" around an already-built darwin binary:
# icon (from the repo's logo.png, via sips+iconutil — both macOS-native, no
# extra deps), Info.plist, the launcher script, and (if SIGN_IDENTITY is
# set) a real bundle-level `codesign`.
#
# codesign is required here instead of the quill-based notarize step already
# used for the raw binaries (see .goreleaser.yaml): quill only signs flat
# Mach-O binaries, not directories/bundles, so it can't produce the bundle
# seal (_CodeSignature/CodeResources over Info.plist + Resources/) that
# Gatekeeper requires for an .app. That seal can only be generated by the
# real `codesign`, which only exists on macOS — hence this script (and the
# CI job that calls it) must run on a macos-latest runner, not ubuntu-latest.
#
# Usage: build-app.sh <binary> <version> <output-dir> [sign-identity]
set -euo pipefail

BINARY="$1"
VERSION="$2"
OUTPUT_DIR="$3"
SIGN_IDENTITY="${4:-}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
APP="$OUTPUT_DIR/Netsk8 Navigator.app"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# --- Icon ---
ICONSET="$(mktemp -d)/AppIcon.iconset"
mkdir -p "$ICONSET"
for sz in 16 32 128 256 512; do
  sips -z "$sz" "$sz" "$REPO_ROOT/logo.png" --out "$ICONSET/icon_${sz}x${sz}.png" >/dev/null
  dbl=$((sz * 2))
  sips -z "$dbl" "$dbl" "$REPO_ROOT/logo.png" --out "$ICONSET/icon_${sz}x${sz}@2x.png" >/dev/null
done
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/AppIcon.icns"

# --- Binary + launcher ---
cp "$BINARY" "$APP/Contents/Resources/netsk8-navigator-bin"
chmod +x "$APP/Contents/Resources/netsk8-navigator-bin"
cp "$SCRIPT_DIR/launcher.sh" "$APP/Contents/MacOS/launcher"
chmod +x "$APP/Contents/MacOS/launcher"

# --- Info.plist / PkgInfo ---
cat >"$APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key><string>launcher</string>
  <key>CFBundleIdentifier</key><string>io.github.robertobado.netsk8-navigator</string>
  <key>CFBundleName</key><string>Netsk8 Navigator</string>
  <key>CFBundleDisplayName</key><string>Netsk8 Navigator</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>${VERSION}</string>
  <key>CFBundleVersion</key><string>${VERSION}</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
EOF
printf 'APPL????' >"$APP/Contents/PkgInfo"

# --- Sign (bundle-level, requires real codesign — see header comment) ---
if [ -n "$SIGN_IDENTITY" ]; then
  codesign --deep --force --options runtime --timestamp \
    --sign "$SIGN_IDENTITY" "$APP"
fi

echo "$APP"
